// kprobe.c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <bpf/libbpf.h>
#include "kprobe.bpf.skel.h" // generated by: bpftool gen skeleton kprobe.bpf.o

static volatile sig_atomic_t stop;
static void on_sigint(int sig) { stop = 1; }

// Optional: route libbpf's own logs to stderr (useful while debugging).
static int libbpf_print(enum libbpf_print_level lvl, const char *fmt,
                        va_list ap) {
  return vfprintf(stderr, fmt, ap);
}

int main(void) {
  struct kprobe_bpf *skel;
  int err;

  libbpf_set_print(libbpf_print);

  signal(SIGINT, on_sigint);
  signal(SIGTERM, on_sigint);

  // open + load: the verifier runs here.
  skel = kprobe_bpf__open_and_load();
  if (!skel) {
    fprintf(stderr, "failed to open/load BPF skeleton\n");
    return 1;
  }

  // Auto-attach: libbpf wires up both kprobe/udp_recvmsg and
  // kretprobe/udp_recvmsg from their SEC() names.
  err = kprobe_bpf__attach(skel);
  if (err) {
    fprintf(stderr, "failed to attach BPF programs: %d\n", err);
    kprobe_bpf__destroy(skel);
    return 1;
  }

  printf("Tracing udp_recvmsg. Ctrl-C to stop.\n");
  printf("Latency output:\n");

  // bpf_printk output lands in the kernel trace pipe.
  // system() blocks while streaming; Ctrl-C ends it and returns here.
  system("cat /sys/kernel/debug/tracing/trace_pipe");

  while (!stop)
    sleep(1);

  kprobe_bpf__destroy(skel);
  return 0;
}