#include <stdio.h>
#include <unistd.h>
#include <signal.h>
#include <bpf/libbpf.h>
#include "uprobe.bpf.skel.h" // generated by: bpftool gen skeleton uprobe.bpf.o

static volatile sig_atomic_t stop;
static void on_sigint(int sig) { stop = 1; }

// Optional: route libbpf's own logs to stderr (helpful while debugging).
static int libbpf_print(enum libbpf_print_level lvl, const char *fmt,
                        va_list ap) {
  return vfprintf(stderr, fmt, ap);
}

int main(int argc, char **argv) {
  const char *target_path = (argc > 1) ? argv[1] : "./target";
  const char *func_name = (argc > 2) ? argv[2] : "my_func";
  struct uprobe_bpf *skel;

  libbpf_set_print(libbpf_print);
  signal(SIGINT, on_sigint);

  // open + load: verifier runs here.
  skel = uprobe_bpf__open_and_load();
  if (!skel) {
    fprintf(stderr, "failed to open/load BPF skeleton\n");
    return 1;
  }

  // Attach entry probe to <target_path>:<func_name>.
  // pid = -1 means every process running that binary.
  LIBBPF_OPTS(bpf_uprobe_opts, entry_opts, .func_name = func_name,
              .retprobe = false);
  skel->links.on_my_func_entry = bpf_program__attach_uprobe_opts(
      skel->progs.on_my_func_entry, -1, target_path, 0, &entry_opts);

  // Attach return probe to the same function.
  LIBBPF_OPTS(bpf_uprobe_opts, ret_opts, .func_name = func_name,
              .retprobe = true);
  skel->links.on_my_func_ret = bpf_program__attach_uprobe_opts(
      skel->progs.on_my_func_ret, -1, target_path, 0, &ret_opts);

  if (!skel->links.on_my_func_entry || !skel->links.on_my_func_ret) {
    fprintf(stderr, "failed to attach uprobe/uretprobe to %s:%s\n", target_path,
            func_name);
    uprobe_bpf__destroy(skel);
    return 1;
  }

  printf("Attached to %s:%s. Ctrl-C to stop.\n", target_path, func_name);
  printf("Latency output:\n");

  // bpf_printk output shows up in the kernel trace pipe.
  system("cat /sys/kernel/debug/tracing/trace_pipe");

  while (!stop)
    sleep(1);

  uprobe_bpf__destroy(skel);
  return 0;
}